function Kw = fun_beam2d_Kw(L,b,k0)
%FUN_BEAM2D_KW
%    KW = FUN_BEAM2D_KW(L,B,K0)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Jul-2022 09:52:35

t2 = L.^2;
t3 = L.^3;
t4 = L.*b.*k0.*(1.3e+1./3.5e+1);
t5 = L.*b.*k0.*(9.0./7.0e+1);
t6 = (b.*k0.*t3)./1.05e+2;
t7 = (b.*k0.*t3)./1.4e+2;
t9 = b.*k0.*t2.*(1.1e+1./2.1e+2);
t10 = b.*k0.*t2.*(1.3e+1./4.2e+2);
t8 = -t7;
t11 = -t9;
t12 = -t10;
Kw = reshape([t4,t9,t5,t12,t9,t6,t10,t8,t5,t10,t4,t11,t12,t8,t11,t6],[4,4]);
