function Kt = fun_beam2d_Kt(E,G,A,I,ky,L)
%FUN_BEAM2D_KT
%    KT = FUN_BEAM2D_KT(E,G,A,I,KY,L)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Jul-2022 09:52:36

t2 = L.^2;
t3 = L.^3;
t4 = 1.0./L;
t5 = E.*I.*ky.*3.0;
t6 = E.*I.*ky.*6.0;
t7 = E.*I.*ky.*1.2e+1;
t8 = A.*G.*t2;
t9 = A.*G.*t3;
t10 = L.*t7;
t11 = -t8;
t12 = t5+t8;
t13 = t7+t8;
t15 = t9+t10;
t14 = t6+t11;
t16 = 1.0./t13;
t17 = 1.0./t15;
t18 = A.*E.*G.*I.*t16.*6.0;
t20 = A.*E.*G.*I.*t17.*1.2e+1;
t22 = E.*I.*t4.*t12.*t16.*4.0;
t23 = E.*I.*t4.*t14.*t16.*2.0;
t19 = -t18;
t21 = -t20;
t24 = -t23;
Kt = reshape([t20,t18,t21,t18,t18,t22,t19,t24,t21,t19,t20,t19,t18,t24,t19,t22],[4,4]);
