function ft = fun_truss1d_ft(E,alpha,L,A,p,theta)
%FUN_TRUSS1D_FT
%    FT = FUN_TRUSS1D_FT(E,ALPHA,L,A,P,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Jul-2022 09:51:21

t2 = A.*E.*alpha.*theta;
ft = [-t2;t2];
